version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    container_name: pgdb
    environment:
      POSTGRES_USER: ravdes
      POSTGRES_PASSWORD: ravdes123
      POSTGRES_DB: tictacdb
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data


